language: cpp
sudo: true

branches:
  only:
  - master

cache:
- directories:
  - $HOME/.cache

addons:
  apt:
    packages:
      - gdb

script:
  - export AWS_KVS_LOG_LEVEL=7
  - make
  - ulimit -c unlimited -S
  - timeout --signal=SIGABRT 20m ./kvspic_test --gtest_filter="-TimerQueueFunctionalityTest.*:HeapPerfTest.*"

after_failure:
  - for i in $(find ./ -maxdepth 1 -name 'core*' -print); do gdb $(pwd)/kvspic_test core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done;

matrix:
  # MemorySanitizer and Thread sanitizer are still WIP
  allow_failures:
    - env: allowTestFail=true

  include:
    # MacOS Builds
    - name: "OSX GCC"
      os: osx
      compiler: gcc
      before_script:
        - mkdir build && cd build && cmake .. -DBUILD_TEST=TRUE
      script:
        - make
        - AWS_KVS_LOG_LEVEL=7 ./kvspic_test --gtest_filter="-TimerQueueFunctionalityTest.*:HeapPerfTest.*"
      after_failure: skip # timeout not available on MacOS

    - name: "OSX Clang"
      os: osx
      compiler: clang
      before_script:
        - mkdir build && cd build && cmake .. -DBUILD_TEST=TRUE -DCOMPILER_WARNINGS=TRUE
      script:
        - make
        - AWS_KVS_LOG_LEVEL=7 ./kvspic_test --gtest_filter="-TimerQueueFunctionalityTest.*:HeapPerfTest.*"
      after_failure: skip # timeout not available on MacOS

    # Code Coverage
    - name: "Linux GCC Code Coverage"
      os: linux
      compiler: gcc
      before_script:
        - mkdir build && cd build && cmake .. -DCODE_COVERAGE=TRUE -DBUILD_TEST=TRUE
      after_success:
        - for test_file in $(find CMakeFiles/kvspic.dir CMakeFiles/kvspicClient.dir CMakeFiles/kvspicState.dir CMakeFiles/kvspicUtils.dir -name '*.gcno'); do gcov $test_file; done
        - bash <(curl -s https://codecov.io/bash)

    # AddressSanitizer
    - name: "Linux Clang AddressSanitizer"
      os: linux
      compiler: clang
      # env: ASAN_OPTIONS=detect_odr_violation=0:detect_leaks=1
      before_script: mkdir build && cd build && cmake .. -DBUILD_TEST=TRUE -DADDRESS_SANITIZER=TRUE

    # UndefinedBehaviorSanitizer
    - name: "Linux Clang UndefinedBehaviorSanitizer"
      os: linux
      compiler: clang
      env: UBSAN_OPTIONS=halt_on_error=1:suppressions=../src/utils/tst/suppressions/UBSAN.supp
      before_script: mkdir build && cd build && cmake .. -DBUILD_TEST=TRUE -DUNDEFINED_BEHAVIOR_SANITIZER=TRUE

    # MemorySanitizer
    - name: "Linux Clang MemorySanitizer"
      os: linux
      compiler: clang
      env: allowTestFail=true
      before_script: mkdir build && cd build && cmake .. -DBUILD_TEST=TRUE -DMEMORY_SANITIZER=TRUE

    # ThreadSanitizer
    - name: "Linux Clang ThreadSanitizer"
      os: linux
      compiler: clang
      env: TSAN_OPTIONS=halt_on_error=1:suppressions=../src/utils/tst/suppressions/TSAN.supp
      before_script: mkdir build && cd build && cmake .. -DBUILD_TEST=TRUE -DTHREAD_SANITIZER=TRUE
      script:
        - make
        - AWS_KVS_LOG_LEVEL=7 ./kvspic_test --gtest_break_on_failure --gtest_filter="-TimerQueueFunctionalityTest.*:HeapPerfTest.*:ThreadFunctionalityTest.ThreadCreateAndCancel"

    # Old Version GCC 4.4
    - name: "Linux GCC 4.4 Build"
      os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-4.4
            - gdb
      compiler: gcc
      before_script: export CC=gcc-4.4 && mkdir build && cd build && cmake .. -DBUILD_TEST=TRUE

    # Cross-compilation to ARM, no tests are run
    - name: "ARM Cross-compilation"
      os: linux
      addons:
        apt:
          packages:
            - gcc-arm-linux-gnueabi
            - g++-arm-linux-gnueabi
            - binutils-arm-linux-gnueabi
      compiler: gcc
      before_script:
        - export CC=arm-linux-gnueabi-gcc CXX=arm-linux-gnueabi-g++
        - mkdir build && cd build
        - cmake .. -DBUILD_TEST=TRUE
      script: make

    # Windows build
    - name: "Windows MSVC"
      os: windows
      script:
          - unset CC CC_FOR_BUILD CXX CXX_FOR_BUILD # We want to use MSVC
          - .github/build_windows.bat
          - export "AWS_KVS_LOG_LEVEL=7"
          - cd build && ./kvspic_test.exe --gtest_filter="-TimerQueueFunctionalityTest.*:HeapPerfTest.*:PermutatedStreamInfo/StateTransitionFunctionalityTest.ControlPlaneServiceCallExhaustRetry*"
